#!/bin/sh
#
# Plugin to monitor the number of users stored in the cassandra CF.

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

HOME=/tmp/
cd $HOME

# If run with the "config"-parameter, give out information on how the
# graphs should look.

if [ "$1" = "config" ]; then
        echo 'graph_title Cassandra users'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel cassandra users'
        echo 'graph_category OAE'
        echo 'users.label users'
        exit 0
fi

# Get the data from Cassandra
# Note that we cannot use the Principals library as that will contain groups as well.
# Each user will have at least 1 login strategy associated to it, so
# we can simply count the number of rows in that table.
CASSANDRA_CONF=/etc/cassandra/cassandra.yaml nodetool --host db0 cfstats | grep --color=never -A 4 'AuthenticationUserLoginId' | grep --color=never 'Number of Keys' | awk {'print $5'}
