#!/usr/bin/env ruby

require 'rubygems'
require 'redis'
require 'yaml'

redis_contructor_info = {}

configFilePath = File.join(File::SEPARATOR,"etc","munin","plugin-conf.d","redis.conf")
if (File.exists?(configFilePath))
  redis_constructor_info = YAML.load(File.open(configFilePath))
else
  $0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
  ip, port = $1, $2
  ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
  port = port.nil? ? 6379 : port
  redis_constructor_info = { :host => ip, :port => port }
end

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis keys"
  puts "graph_category redis"
  puts "graph_vlabel keys used"
  puts "graph_info This graph monitors the total number of keys"
  puts "graph_args --base 1024 -l 0"

  puts "keys.label keys"
  puts "keys.info Amount of keys in redis"
  puts "keys.type GAUGE"
  puts "keys.min 0"
  puts "keys.draw AREA"

else
  redis = Redis.new(redis_constructor_info)
  info  = redis.dbsize

  puts "keys.value" + " " + info.to_s
end