#!/bin/bash
#
# Checks if all the proxied servers are marked as either UP or OPEN
# This script will return:
#   *  CRITICAL:    when one of the proxied servers is not in UP or OPEN mode
#   *  OK:          if all of the proxied servers are in UP or OPEN mode
# 
#
# Usage:
#    ./check_haproxy_status

data=$(curl -s -u haproxy:haproxy "http://localhost/;csv" | tail -n+2)
for line in $data ; do
    instance=$(echo $line | cut -f 2 -d ",")
    status=$(echo $line | cut -f 18 -d ",")

    if [[ "$status" != "UP" ]] && [[  "$status" != "OPEN" ]] ; then
        echo "CRITICIAL:$instance is in $status mode";
        exit 2;
    fi
done

echo "OK";
exit 0;
