#!/bin/bash
#
# Simple nagios check that greps the elasticsearch logs for slow queries.
#
# Example lines
# Apr 19 09:54:20 search0 [2013-04-19 09:54:20,086][WARN ][index.search.slowlog.query] [Apollo] [twitter][3] took[17.7ms], took_millis[17], types[tweet], stats[], search_type[QUERY_AND_FETCH], total_shards[1], source[{"query":{"filtered":{"query":{"query_string":{"query":"Elastic"}},"filter":{"term":{"user":"kimchy"}}}}}], extra_source[],
# Apr 19 09:54:20 search0 [2013-04-19 09:54:20,099][WARN ][index.search.slowlog.fetch] [Apollo] [twitter][3] took[24.8ms], took_millis[24], types[tweet], stats[], search_type[QUERY_AND_FETCH], total_shards[1], source[{"query":{"filtered":{"query":{"query_string":{"query":"Elastic"}},"filter":{"term":{"user":"kimchy"}}}}}], extra_source[],
# Apr 19 09:54:20 search0 [2013-04-19 09:54:20,846][WARN ][index.search.slowlog.fetch] [Apollo] [twitter][3] took[22.4ms], took_millis[22], types[tweet], stats[], search_type[QUERY_AND_FETCH], total_shards[1], source[{"query":{"filtered":{"query":{"query_string":{"query":"Elastic"}},"filter":{"term":{"user":"kimchy"}}}}}], extra_source[],


HOUR=`date +"%Y-%m-%d %H:"`
TODAY=`date +"%Y-%m-%d"`
LOGDIR="/var/log/rsyslog"
NODE="search0-10.224.16.164"

# Determine the correct file and term to grep for.
if [ "$1" = "query" ] ; then
     FILE="local1-$TODAY.log"
     TERM='index.search.slowlog.query'
elif [ "$1" = "index" ] ; then
     FILE="local2-$TODAY.log"
     TERM='index.search.slowlog.index'
elif [ "$1" = "index_merge" ] ; then
     FILE="local3-$TODAY.log"
     TERM='index.search.slowlog.index_merge'
fi

FILE="$LOGDIR/$NODE/$FILE"

# If the file does not exist, we haven't seen a slow query all day and can quit early..
if [ ! -f "$FILE" ] ; then
     echo "OK"
     exit 0
fi

# Grep for the term and count the number of times we have a hit.
lines=$(grep $TERM $FILE | grep "$HOUR" | wc -l)

# Depending on the number of lines we exit differently.
if [[ $lines -gt 5 ]] ; then
    echo "CRITICAL:Slow queries $lines"
    exit 2
elif [[ $lines -gt 3 ]] ; then
    echo "WARNING:Slow queries $lines"
    exit 1
else
    echo "OK"
    exit 0
fi
