#! /bin/bash
#
# alerts if file exists
# david.stringer@researchresearch.com
#

PROGNAME=$(basename $0)
PROGPATH=$(echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,')

. $PROGPATH/utils.sh

if [ "$1" = "" ]
then
  echo " Use : $PROGNAME <file>"
  exit $STATE_UNKNOWN
fi

if [ -f "$1" ]
then
  echo "CRITICAL - $1 : EXISTS :: $1"
  exit $STATE_CRITICAL
else
  echo "OK : $1 Does NOT exist "
  exit $STATE_OK
fi

